variables:
  # To make npm test to not to start in watch mode
  # https://create-react-app.dev/docs/running-tests/#continuous-integration
  CI: "true"

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - test
  - package

lint:
  image: docker.atixlabs.com/node:12.16.0-alpine
  stage: test
  script:
    - npm run eslint
  except:
    - schedules

test:
  image: docker.atixlabs.com/node:12.16.0-alpine
  stage: test
  script:
    - npm run test
  except:
    - schedules

package:
  image: docker.atixlabs.com/node:12.16.0-alpine
  stage: package
  services:
    - docker.atixlabs.com/docker:19.03.1-dind
  script:
    - apk add docker
    - docker login -u gitlabci -p $CI_JOB_TOKEN $CI_REGISTRY
    - npm run docker:build
    - npm run docker:push
  only:
    refs:
      # Only run on develop, release/x.y.x and hotfix/xxxx
      - COA-1746-Dockerize-Front
      - develop
      - /^release.*$/
      - /^hotfix.*$/
