variables:

  # To make npm test to not to start in watch mode
  # https://create-react-app.dev/docs/running-tests/#continuous-integration
  CI: "true"

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - test

lint:
  image: node:12.16.0
  stage: test
  script:
    - npm run eslint
  except:
    - schedules

test:
  image: node:12.16.0
  stage: test
  script:
    - npm run test
  except:
    - schedules
