  COA-1318-FUENTE[m
  COA-1367[m
  COA-1374-1385-fixing-conflicts[m
  COA-1383-MODAL[m
  COA-1412[m
  COA-1434-Hiding-the-execute-button-when-grace-period[m
  COA-MEMBER-LIST[m
  Release/2.6.0[m
  Release/2.7.0[m
  Release/2.8.0[m
  Release/2.9.0[m
  Release/3.0.0[m
  Release/3.1.0[m
* [32mdevelop[m
  feature/COA-1372-Add-Daos-Option-Menu[m
  feature/COA-1373-Navigate-from-DAO-card-to-detail[m
  feature/COA-1374-List-all-the-proposals-once-you-go-into-DAO[m
  feature/COA-1380-hiding-dao-icon-if-it-doesnt-has-daos[m
  feature/COA-1385-adding-dynamic-data-to-proposal-card[m
  feature/COA-1386-new-member-proposal-flow[m
  feature/COA-1388-new-create-dao-proposal-with-signing-flow[m
  feature/COA-1389-vote-proposal-flow[m
  feature/COA-1393-adding-remaining-voting-time-to-the-proposal[m
  feature/COA-1396-1399-executing-button-with-validations-and-processing-a-proposal[m
  feature/COA-1397-adding-members-tab-to-the-dao-detail[m
  feature/COA-1400-new-member-proposal-with-signing-flow[m
  feature/COA-1410-changin-applicant-input-as-a-user-searcher[m
  feature/COA-1411-adding-handler-for-proposal-creation[m
  feature/COA-1414-add-participants-to-the-proposal-card[m
  feature/COA-1416-cleaning-values-when-cancel-modal[m
  feature/COA-1418-redirect-the-tab-when-successful-submission[m
  feature/COA-1419-updating-members-indicator-on-dao-card[m
  feature/COA-1420-process-proposal-when-negative-or-draw-voting[m
  feature/COA-1422-adding-dates-to-proposal-content[m
  feature/COA-1426-1415-participants-voting-getter[m
  feature/COA-1427-adding-pending-status-when-proposal-created[m
  feature/COA-1435-adding-vote-handler-tx[m
  feature/COA-1436-update-open-proposals-on-dao-list[m
  fix/COA-1424-1425-register-stepper-re-rendering-many-times[m
